# Generated by Django 3.2.9 on 2021-11-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('username', models.CharField(choices=[('Engineering', 'Engineering'), ('Agriculture', 'Agriculture'), ('Accounting', 'Accounting'), ('Tresurer', 'Tresurer'), ('MPDC', 'MPDC'), ('MCTC', 'MCTC'), ('MCR', 'MCR'), ('Mayor', 'Mayor'), ('Tourism', 'Tourism')], max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
